name: Quick Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install dependencies
        run: |
          cd website
          npm install

      - name: Build project
        run: |
          cd website
          npm run build

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: website/build

      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@v4
